export const exhibitionData = [
  {
    src: "/assets/exhibition/1.svg",
    title: "Swan",
    brief: "Golden",
    price: "42,350",
    category: "all",
  },
  {
    src: "/assets/exhibition/2.svg",
    title: "Sunset",
    brief: "Red",
    price: "12,350",
    category: "all",
  },
  {
    src: "/assets/exhibition/3.svg",
    title: "Moon",
    brief: "Silver",
    price: "22,350",
    category: "all",
  },
  {
    src: "/assets/exhibition/4.svg",
    title: "Stars",
    brief: "Blue",
    price: "32,350",
    category: "all",
  },
  {
    src: "/assets/exhibition/1.svg",
    title: "Swan",
    brief: "Golden",
    price: "42,350",
    category: "all",
  },
  {
    src: "/assets/exhibition/2.svg",
    title: "Sunset",
    brief: "Red",
    price: "12,350",
    category: "all",
  },
  {
    src: "/assets/exhibition/3.svg",
    title: "Moon",
    brief: "Silver",
    price: "22,350",
    category: "all",
  },
  {
    src: "/assets/exhibition/4.svg",
    title: "Stars",
    brief: "Blue",
    price: "32,350",
    category: "all",
  },
  {
    src: "/assets/exhibition/1.svg",
    title: "Swan",
    brief: "Golden",
    price: "42,350",
    category: "whimsical",
  },
  {
    src: "/assets/exhibition/2.svg",
    title: "Swan",
    brief: "Golden",
    price: "42,350",
    category: "whimsical",
  },
  {
    src: "/assets/exhibition/3.svg",
    title: "Swan",
    brief: "Golden",
    price: "42,350",
    category: "landscape",
  },
  {
    src: "/assets/exhibition/4.svg",
    title: "Swan",
    brief: "Golden",
    price: "42,350",
    category: "landscape",
  },
  {
    src: "/assets/exhibition/1.svg",
    title: "Swan",
    brief: "Golden",
    price: "42,350",
    category: "figures",
  },
  {
    src: "/assets/exhibition/2.svg",
    title: "Swan",
    brief: "Golden",
    price: "42,350",
    category: "figures",
  },
  {
    src: "/assets/exhibition/3.svg",
    title: "Swan",
    brief: "Golden",
    price: "42,350",
    category: "figures",
  },
];

export const galleryData = [
  "/assets/gallery/1.svg",
  "/assets/gallery/2.svg",
  "/assets/gallery/3.svg",
  "/assets/gallery/1.svg",
  "/assets/gallery/2.svg",
  "/assets/gallery/3.svg",
  "/assets/gallery/1.svg",
];
